// Generated by CoffeeScript 1.8.0
(function() {
  (function($) {
    var memberCount, regularCount;
    $(document).ready(function() {
      return $('#simple-menu').sidr({
        side: 'right'
      });
    });
    $('.page').on('click', function() {
      return $.sidr('close');
    });
    $(window).on('resize', function() {
      if ($('body').hasClass('sidr-open') && $(window).width() >= 768) {
        return $.sidr('close');
      }
    });
    memberCount = $('.member-count');
    regularCount = $('.reg-count');
    console.log('test');
    memberCount.on('blur', function() {});
    return console.log(memberCount.val());
  })(jQuery);

}).call(this);
