// Generated by CoffeeScript 1.8.0
(function() {
  (function($) {
    var $blip, memberCount, regularCount;
    $(document).ready(function() {
      return $('#simple-menu').sidr({
        side: 'right'
      });
    });
    $('.page').on('click', function() {
      return $.sidr('close');
    });
    $(window).on('resize', function() {
      if ($('body').hasClass('sidr-open') && $(window).width() >= 768) {
        return $.sidr('close');
      }
    });
    memberCount = $('.member-count');
    regularCount = $('.reg-count');
    console.log('test');
    memberCount.on('blur', function() {
      return console.log(memberCount.val());
    });
    $blip = $('.blip');
    $('#primary-menu>li').on('mouseover', function() {
      return $blip.css({
        left: $(this).offset().left - $(this).parent().offset().left,
        width: $(this).width() - 14
      });
    });
    return $('#primary-menu').on('mouseout', function() {
      return $('.blip').css({
        left: 0,
        width: 50
      });
    });
  })(jQuery);

}).call(this);
