// Generated by CoffeeScript 1.8.0
(function() {
  (function($) {
    var $blip, memberCount, memberCountChange, regularCount, regularCountChange, totalNumberOfAttendees;
    $(document).ready(function() {
      return $('#simple-menu').sidr({
        side: 'right'
      });
    });
    $('.page').on('click', function() {
      return $.sidr('close');
    });
    $(window).on('resize', function() {
      if ($('body').hasClass('sidr-open') && $(window).width() >= 768) {
        return $.sidr('close');
      }
    });
    memberCountChange = $('.member-count');
    regularCountChange = $('.reg-count');
    memberCount = memberCountChange.val();
    regularCount = regularCountChange.val();
    totalNumberOfAttendees = memberCount + regularCount;
    memberCountChange.on('change', function() {
      memberCount;
      return console.log(totalNumberOfAttendees);
    });
    regularCountChange.on('change', function() {
      regularCount;
      return console.log(totalNumberOfAttendees);
    });
    $blip = $('.blip');
    $('#primary-menu>li').on('mouseover', function() {
      return $blip.css({
        left: $(this).offset().left - $(this).parent().offset().left,
        width: $(this).width() - 14
      });
    });
    return $('#primary-menu').on('mouseout', function() {
      return $('.blip').css({
        left: 0,
        width: 50
      });
    });
  })(jQuery);

}).call(this);
